plugins {
    id 'com.android.library'
    id 'com.chaquo.python'
}

android {
    namespace 'com.fongmi.chaquo'
    compileSdk {
        version = release(37)
    }

    flavorDimensions = ["mode", "abi"]

    defaultConfig {
        minSdk 24
        targetSdk 37
        python {
            version = "3.10"
            pip {
                install "lxml"
                install "ujson"
                install "pyquery"
                install "requests"
                install "jsonpath-ng"
                install "cachetools"
                install 'pycryptodome'
                install 'beautifulsoup4'
                install 'brotli'
                install 'charset-normalizer'
                install 'js2py'
            }
        }
    }

    productFlavors {
        leanback {
            dimension "mode"
        }
        mobile {
            dimension "mode"
        }
        arm64_v8a {
            dimension "abi"
            ndk { abiFilters "arm64-v8a" }
        }
        armeabi_v7a {
            dimension "abi"
            ndk { abiFilters "armeabi-v7a" }
        }
    }

    sourceSets {
        main {
            python.srcDirs = ["src/main/python"]
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation project(':catvod')
}
